### Course list
GET localhost:8080/course/list

### Course by id
GET localhost:8080/course/get/1


### Student create
POST localhost:8080/course/create
Content-Type: application/json

{
  "name": "uwgef",
  "price": 15,
  "duration": 10
}




### Student update
PUT localhost:8080/student/update/2
Content-Type: application/json

{
  "name": "Qo'y",
  "surname": "Qo'chqorov"
}

### Course delete
DELETE localhost:8080/course/delete/2

###
GET localhost:8080/course/get-by-duration-between?fromDuration=1&toDuration=10

### Get by name
GET localhost:8080/course/get-by-name/Java
